name: user_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  json_annotation: ^4.8.1
  dio: ^5.4.0
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Firebase dependencies
  firebase_core: ^2.24.0
  firebase_auth: ^4.15.0

  # Google Sign-In
  google_sign_in: ^6.1.5

  # Platform-specific dependencies
  crypto: ^3.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
